# Generated by Django 2.2.1 on 2019-07-14 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_A1c', models.IntegerField(blank=True, null=True)),
                ('insulin_sens', models.IntegerField(blank=True, null=True)),
                ('carb_ratio', models.IntegerField(blank=True, null=True)),
                ('basal', models.IntegerField(blank=True, null=True)),
                ('doctor', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
