# Generated by Django 2.2.1 on 2019-06-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.DateField(blank=True)),
                ('meal', models.CharField(blank=True, choices=[('no_meal', 'No Meal'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime'), ('snack', 'Snack')], max_length=10)),
                ('curr_BSL', models.IntegerField(blank=True)),
                ('diff_BSL', models.IntegerField(blank=True)),
                ('correction_insulin', models.IntegerField(blank=True)),
                ('total_carb', models.IntegerField(blank=True)),
                ('carb_ratio', models.IntegerField(blank=True)),
                ('insulin_dose', models.IntegerField(blank=True)),
                ('total_insulin', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
