# Generated by Django 2.2.1 on 2019-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinsulin',
            name='meal',
            field=models.CharField(blank=True, choices=[('No_meal', 'No Meal'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Bedtime', 'Bedtime'), ('Snack', 'Snack')], max_length=10),
        ),
    ]
